//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Reqiured")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required")]
        public string FName { get; set; }

        [Required(ErrorMessage ="Required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage ="enter value")]
        [MinLength(11,ErrorMessage = "Mobile number must be 11 digits")]
        public string Mobile { get; set; }

        

        public string Description { get; set; }

    }
}
